/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Aggregated statuses of the first builds with this change. Fairly expensive to compute.
type ChangeStatus struct {
	RunningSuccessfullyBuilds int32   `json:"runningSuccessfullyBuilds,omitempty"`
	PendingBuildTypes         int32   `json:"pendingBuildTypes,omitempty"`
	TotalProblems             int32   `json:"totalProblems,omitempty"`
	NewFailedTests            int32   `json:"newFailedTests,omitempty"`
	OtherFailedTests          int32   `json:"otherFailedTests,omitempty"`
	QueuedBuildsCount         int32   `json:"queuedBuildsCount,omitempty"`
	CriticalBuilds            *Builds `json:"criticalBuilds,omitempty"`
	NotCriticalBuilds         *Builds `json:"notCriticalBuilds,omitempty"`
	NewTestsFailedBuilds      *Builds `json:"newTestsFailedBuilds,omitempty"`
	CompilationErrorBuilds    *Builds `json:"compilationErrorBuilds,omitempty"`
	SuccessfulBuilds          int32   `json:"successfulBuilds,omitempty"`
	FinishedBuilds            int32   `json:"finishedBuilds,omitempty"`
	RunningBuilds             int32   `json:"runningBuilds,omitempty"`
	FailedBuilds              int32   `json:"failedBuilds,omitempty"`
	CancelledBuilds           int32   `json:"cancelledBuilds,omitempty"`
}
