/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents group approval rule and its current status for the given build.
type GroupApprovalRule struct {
	Group                  *Group `json:"group,omitempty"`
	RequiredApprovalsCount int32  `json:"requiredApprovalsCount,omitempty"`
	CurrentlyApprovedBy    *Users `json:"currentlyApprovedBy,omitempty"`
}
