/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// List of metadata on artifacts downloaded from [or provided by] a build.
type DownloadInfo struct {
	Build        *Build                 `json:"build,omitempty"`
	ArtifactInfo []ArtifactDownloadInfo `json:"artifactInfo,omitempty"`
	Count        int32                  `json:"count,omitempty"`
}
