/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a metric tag.
type MetricTag struct {
	Name  string `json:"name,omitempty"`
	Value string `json:"value,omitempty"`
}
