/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents test metadata (package, method, class, and so on).
type ParsedTestName struct {
	TestPackage            string `json:"testPackage,omitempty"`
	TestSuite              string `json:"testSuite,omitempty"`
	TestClass              string `json:"testClass,omitempty"`
	TestShortName          string `json:"testShortName,omitempty"`
	TestNameWithoutPrefix  string `json:"testNameWithoutPrefix,omitempty"`
	TestMethodName         string `json:"testMethodName,omitempty"`
	TestNameWithParameters string `json:"testNameWithParameters,omitempty"`
}
