/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// Represents an authentication token.
type Token struct {
	Name                   string                  `json:"name,omitempty"`
	CreationTime           time.Time               `json:"creationTime,omitempty"`
	Value                  string                  `json:"value,omitempty"`
	ExpirationTime         time.Time               `json:"expirationTime,omitempty"`
	PermissionRestrictions *PermissionRestrictions `json:"permissionRestrictions,omitempty"`
}
