/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a locator string for filtering Change entities.
type ChangeLocator struct {
	// Project (direct or indirect parent) locator.
	AffectedProject string `json:"affectedProject,omitempty"`
	// Build locator.
	Build string `json:"build,omitempty"`
	// Build type locator.
	BuildType string `json:"buildType,omitempty"`
	Comment   string `json:"comment,omitempty"`
	// For paginated calls, how many entities to return per page.
	Count int32  `json:"count,omitempty"`
	File  string `json:"file,omitempty"`
	// Entity ID.
	Id              int32  `json:"id,omitempty"`
	InternalVersion string `json:"internalVersion,omitempty"`
	// Supply multiple locators and return a union of the results.
	Item string `json:"item,omitempty"`
	// Is pending.
	Pending bool `json:"pending,omitempty"`
	// Project locator.
	Project string `json:"project,omitempty"`
	// Commit SHA since which the changes should be returned.
	SinceChange string `json:"sinceChange,omitempty"`
	// For paginated calls, from which entity to start rendering the page.
	Start int32 `json:"start,omitempty"`
	// User locator.
	User string `json:"user,omitempty"`
	// VCS side username.
	Username string `json:"username,omitempty"`
	// VCS root locator.
	VcsRoot string `json:"vcsRoot,omitempty"`
	// VCS instance locator.
	VcsRootInstance string `json:"vcsRootInstance,omitempty"`
	Version         string `json:"version,omitempty"`
}
