/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents an investigation scope.
type ProblemScope struct {
	Project    *Project    `json:"project,omitempty"`
	BuildTypes *BuildTypes `json:"buildTypes,omitempty"`
	BuildType  *BuildType  `json:"buildType,omitempty"`
}
