/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a cloud agent profile.
type CloudProfile struct {
	Id              string       `json:"id,omitempty"`
	Name            string       `json:"name,omitempty"`
	CloudProviderId string       `json:"cloudProviderId,omitempty"`
	Href            string       `json:"href,omitempty"`
	Project         *Project     `json:"project,omitempty"`
	Images          *CloudImages `json:"images,omitempty"`
}
