/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a plugin.
type Plugin struct {
	Name        string      `json:"name,omitempty"`
	DisplayName string      `json:"displayName,omitempty"`
	Version     string      `json:"version,omitempty"`
	LoadPath    string      `json:"loadPath,omitempty"`
	Parameters  *Properties `json:"parameters,omitempty"`
}
