/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// Represents a locator string for filtering Mute entities.
type MuteLocator struct {
	// Project (direct or indirect parent) locator.
	AffectedProject string `json:"affectedProject,omitempty"`
	// yyyyMMddTHHmmss+ZZZZ
	CreationDate time.Time `json:"creationDate,omitempty"`
	Id           int32     `json:"id,omitempty"`
	// Supply multiple locators and return a union of the results.
	Item string `json:"item,omitempty"`
	// Problem locator.
	Problem string `json:"problem,omitempty"`
	// Project (direct parent) locator.
	Project string `json:"project,omitempty"`
	// User who muted this test.
	Reporter   string `json:"reporter,omitempty"`
	Resolution string `json:"resolution,omitempty"`
	// Test locator.
	Test  string `json:"test,omitempty"`
	Type_ string `json:"type,omitempty"`
	// yyyyMMddTHHmmss+ZZZZ
	UnmuteDate time.Time `json:"unmuteDate,omitempty"`
}
