/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a related entity.
type RelatedEntity struct {
	Type_      string     `json:"type,omitempty"`
	Unknown    bool       `json:"unknown,omitempty"`
	InternalId string     `json:"internalId,omitempty"`
	Text       string     `json:"text,omitempty"`
	Build      *Build     `json:"build,omitempty"`
	BuildType  *BuildType `json:"buildType,omitempty"`
	Project    *Project   `json:"project,omitempty"`
	User       *User      `json:"user,omitempty"`
	Group      *Group     `json:"group,omitempty"`
	Problem    *Problem   `json:"problem,omitempty"`
	Agent      *Agent     `json:"agent,omitempty"`
	VcsRoot    *VcsRoot   `json:"vcsRoot,omitempty"`
	Change     *Change    `json:"change,omitempty"`
	AgentPool  *AgentPool `json:"agentPool,omitempty"`
}
