/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a revision related to a VCS change.
type Revision struct {
	Version         string           `json:"version,omitempty"`
	InternalVersion string           `json:"internalVersion,omitempty"`
	VcsBranchName   string           `json:"vcsBranchName,omitempty"`
	VcsRootInstance *VcsRootInstance `json:"vcs-root-instance,omitempty"`
	CheckoutRules   string           `json:"checkout-rules,omitempty"`
}
