/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents the dependency/queue settings with which this build has been started.
type BuildTriggeringOptions struct {
	CleanSources                          bool        `json:"cleanSources,omitempty"`
	CleanSourcesInAllDependencies         bool        `json:"cleanSourcesInAllDependencies,omitempty"`
	RebuildAllDependencies                bool        `json:"rebuildAllDependencies,omitempty"`
	RebuildFailedOrIncompleteDependencies bool        `json:"rebuildFailedOrIncompleteDependencies,omitempty"`
	QueueAtTop                            bool        `json:"queueAtTop,omitempty"`
	FreezeSettings                        bool        `json:"freezeSettings,omitempty"`
	TagDependencies                       bool        `json:"tagDependencies,omitempty"`
	RebuildDependencies                   *BuildTypes `json:"rebuildDependencies,omitempty"`
}
