/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents an instance of a failed test in the specific build.
type ProblemOccurrence struct {
	Id                    string   `json:"id,omitempty"`
	Type_                 string   `json:"type,omitempty"`
	Identity              string   `json:"identity,omitempty"`
	Href                  string   `json:"href,omitempty"`
	Muted                 bool     `json:"muted,omitempty"`
	CurrentlyInvestigated bool     `json:"currentlyInvestigated,omitempty"`
	CurrentlyMuted        bool     `json:"currentlyMuted,omitempty"`
	LogAnchor             string   `json:"logAnchor,omitempty"`
	NewFailure            bool     `json:"newFailure,omitempty"`
	Details               string   `json:"details,omitempty"`
	AdditionalData        string   `json:"additionalData,omitempty"`
	Problem               *Problem `json:"problem,omitempty"`
	Mute                  *Mute    `json:"mute,omitempty"`
	Build                 *Build   `json:"build,omitempty"`
}
