/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents an agent pool instance.
type AgentPool struct {
	Id           int32     `json:"id,omitempty"`
	Name         string    `json:"name,omitempty"`
	Href         string    `json:"href,omitempty"`
	MaxAgents    int32     `json:"maxAgents,omitempty"`
	OwnerProject *Project  `json:"ownerProject,omitempty"`
	Projects     *Projects `json:"projects,omitempty"`
	Agents       *Agents   `json:"agents,omitempty"`
	Locator      string    `json:"locator,omitempty"`
}
