/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a VCS root assigned to this build configuration.
type VcsRootEntry struct {
	Id            string   `json:"id,omitempty"`
	Inherited     bool     `json:"inherited,omitempty"`
	VcsRoot       *VcsRoot `json:"vcs-root,omitempty"`
	CheckoutRules string   `json:"checkout-rules,omitempty"`
}
