/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents an investigation of a build problem.
type Investigation struct {
	Id          string         `json:"id,omitempty"`
	State       string         `json:"state,omitempty"`
	Href        string         `json:"href,omitempty"`
	Assignee    *User          `json:"assignee,omitempty"`
	Assignment  *Comment       `json:"assignment,omitempty"`
	Scope       *ProblemScope  `json:"scope,omitempty"`
	Target      *ProblemTarget `json:"target,omitempty"`
	Resolution  *Resolution    `json:"resolution,omitempty"`
	Responsible *User          `json:"responsible,omitempty"`
}
