/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a test.
type Test struct {
	Id              string           `json:"id,omitempty"`
	Name            string           `json:"name,omitempty"`
	Mutes           *Mutes           `json:"mutes,omitempty"`
	Investigations  *Investigations  `json:"investigations,omitempty"`
	TestOccurrences *TestOccurrences `json:"testOccurrences,omitempty"`
	ParsedTestName  *ParsedTestName  `json:"parsedTestName,omitempty"`
	Href            string           `json:"href,omitempty"`
	Locator         string           `json:"locator,omitempty"`
}
