/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a permission.
type Permission struct {
	Id     string `json:"id,omitempty"`
	Name   string `json:"name,omitempty"`
	Global bool   `json:"global,omitempty"`
}
