/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type BuildStatusUpdate struct {
	Status  string `json:"status,omitempty"`
	Comment string `json:"comment,omitempty"`
}
