/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a license key details.
type LicenseKey struct {
	Valid               bool   `json:"valid,omitempty"`
	Active              bool   `json:"active,omitempty"`
	Expired             bool   `json:"expired,omitempty"`
	Obsolete            bool   `json:"obsolete,omitempty"`
	ExpirationDate      string `json:"expirationDate,omitempty"`
	MaintenanceEndDate  string `json:"maintenanceEndDate,omitempty"`
	Type_               string `json:"type,omitempty"`
	Servers             int32  `json:"servers,omitempty"`
	Agents              int32  `json:"agents,omitempty"`
	UnlimitedAgents     bool   `json:"unlimitedAgents,omitempty"`
	BuildTypes          int32  `json:"buildTypes,omitempty"`
	UnlimitedBuildTypes bool   `json:"unlimitedBuildTypes,omitempty"`
	ErrorDetails        string `json:"errorDetails,omitempty"`
	Key                 string `json:"key,omitempty"`
	RawType             string `json:"rawType,omitempty"`
}
