/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a locator string for filtering Branch entities.
type BranchLocator struct {
	// Is feature branch.
	Branched string `json:"branched,omitempty"`
	// Build locator.
	Build string `json:"build,omitempty"`
	// Build type locator.
	BuildType string `json:"buildType,omitempty"`
	// Is default branch.
	Default_ string `json:"default,omitempty"`
	// Supply multiple locators and return a union of the results.
	Item   string `json:"item,omitempty"`
	Name   string `json:"name,omitempty"`
	Policy string `json:"policy,omitempty"`
}
