/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a locator string for filtering VcsRoot entities.
type VcsRootLocator struct {
	// Project (direct or indirect parent) locator.
	AffectedProject string `json:"affectedProject,omitempty"`
	// For paginated calls, how many entities to return per page.
	Count int32 `json:"count,omitempty"`
	// Entity ID.
	Id         int32  `json:"id,omitempty"`
	InternalId string `json:"internalId,omitempty"`
	// Supply multiple locators and return a union of the results.
	Item string `json:"item,omitempty"`
	// Limit processing to the latest `<lookupLimit>` entities.
	LookupLimit int32  `json:"lookupLimit,omitempty"`
	Name        string `json:"name,omitempty"`
	// Project (direct parent) locator.
	Project  string `json:"project,omitempty"`
	Property string `json:"property,omitempty"`
	// For paginated calls, from which entity to start rendering the page.
	Start int32 `json:"start,omitempty"`
	// Type of VCS (e.g. jetbrains.git).
	Type_ string `json:"type,omitempty"`
	Uuid  string `json:"uuid,omitempty"`
}
