/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// Represents a locator string for filtering User entities.
type UserLocator struct {
	// User group (direct or indirect parent) locator.
	AffectedGroup string `json:"affectedGroup,omitempty"`
	// Return user that has issued this request.
	Current string `json:"current,omitempty"`
	Email   string `json:"email,omitempty"`
	// User group (direct parent) locator.
	Group string `json:"group,omitempty"`
	Id    string `json:"id,omitempty"`
	// Supply multiple locators and return a union of the results.
	Item      string    `json:"item,omitempty"`
	LastLogin time.Time `json:"lastLogin,omitempty"`
	Name      string    `json:"name,omitempty"`
	Property  string    `json:"property,omitempty"`
	// Role locator.
	Role     string `json:"role,omitempty"`
	Username string `json:"username,omitempty"`
}
