/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a relation between a test and the specific build.
type TestOccurrence struct {
	Id                    string           `json:"id,omitempty"`
	Name                  string           `json:"name,omitempty"`
	Status                string           `json:"status,omitempty"`
	Ignored               bool             `json:"ignored,omitempty"`
	Duration              int32            `json:"duration,omitempty"`
	RunOrder              string           `json:"runOrder,omitempty"`
	NewFailure            bool             `json:"newFailure,omitempty"`
	Muted                 bool             `json:"muted,omitempty"`
	CurrentlyMuted        bool             `json:"currentlyMuted,omitempty"`
	CurrentlyInvestigated bool             `json:"currentlyInvestigated,omitempty"`
	Href                  string           `json:"href,omitempty"`
	IgnoreDetails         string           `json:"ignoreDetails,omitempty"`
	Details               string           `json:"details,omitempty"`
	Mute                  *Mute            `json:"mute,omitempty"`
	Build                 *Build           `json:"build,omitempty"`
	FirstFailed           *TestOccurrence  `json:"firstFailed,omitempty"`
	NextFixed             *TestOccurrence  `json:"nextFixed,omitempty"`
	Invocations           *TestOccurrences `json:"invocations,omitempty"`
	Metadata              *TestRunMetadata `json:"metadata,omitempty"`
	LogAnchor             string           `json:"logAnchor,omitempty"`
}
