/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a locator string for filtering AuditEvent entities.
type AuditLocator struct {
	// Use `$help` to get the full list of supported actions.
	Action string `json:"action,omitempty"`
	// Related project locator.
	AffectedProject string `json:"affectedProject,omitempty"`
	// Related build type or template locator.
	BuildType string `json:"buildType,omitempty"`
	// For paginated calls, how many entities to return per page.
	Count int32  `json:"count,omitempty"`
	Id    string `json:"id,omitempty"`
	// Supply multiple locators and return a union of the results.
	Item string `json:"item,omitempty"`
	// Limit processing to the latest `<lookupLimit>` entities.
	LookupLimit int32 `json:"lookupLimit,omitempty"`
	// For paginated calls, from which entity to start rendering the page.
	Start        int32  `json:"start,omitempty"`
	SystemAction string `json:"systemAction,omitempty"`
	// Locator of user who caused the audit event.
	User string `json:"user,omitempty"`
}
