/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a locator string for filtering Node entities.
type TeamCityNodeLocator struct {
	// Supply multiple locators and return a union of the results.
	Item  string `json:"item,omitempty"`
	Role  string `json:"role,omitempty"`
	State string `json:"state,omitempty"`
}
