/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import "os"

// Represents a list of File entities.
type Files struct {
	Count int32      `json:"count,omitempty"`
	Href  string     `json:"href,omitempty"`
	File  []*os.File `json:"file,omitempty"`
}
