/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents an investigation resolution timestamp and details.
type Resolution struct {
	Type_ string `json:"type,omitempty"`
	Time  string `json:"time,omitempty"`
}
