/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a single responsibility of a TeamCity node.
type Responsibility struct {
	Name        string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
}
