/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents links to the next or previous build.
type BuildChange struct {
	NextBuild *Build `json:"nextBuild,omitempty"`
	PrevBuild *Build `json:"prevBuild,omitempty"`
}
