/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a cloud instance image saved with a profile.
type CloudImage struct {
	Id                  string          `json:"id,omitempty"`
	Name                string          `json:"name,omitempty"`
	Href                string          `json:"href,omitempty"`
	Profile             *CloudProfile   `json:"profile,omitempty"`
	Instances           *CloudInstances `json:"instances,omitempty"`
	ErrorMessage        string          `json:"errorMessage,omitempty"`
	AgentTypeId         int32           `json:"agentTypeId,omitempty"`
	AgentPoolId         int32           `json:"agentPoolId,omitempty"`
	OperatingSystemName string          `json:"operatingSystemName,omitempty"`
	Locator             string          `json:"locator,omitempty"`
}
