/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a compatibility relation between the agent and build configuration.
type Compatibility struct {
	Compatible        bool          `json:"compatible,omitempty"`
	Agent             *Agent        `json:"agent,omitempty"`
	BuildType         *BuildType    `json:"buildType,omitempty"`
	UnmetRequirements *Requirements `json:"unmetRequirements,omitempty"`
}
