/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a build configuration run policy and included build configurations.
type CompatibilityPolicy struct {
	Policy     string      `json:"policy,omitempty"`
	BuildTypes *BuildTypes `json:"buildTypes,omitempty"`
}
