/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a group of links to the user's avatars
type UserAvatars struct {
	UrlToSize20 string `json:"urlToSize20,omitempty"`
	UrlToSize28 string `json:"urlToSize28,omitempty"`
	UrlToSize32 string `json:"urlToSize32,omitempty"`
	UrlToSize40 string `json:"urlToSize40,omitempty"`
	UrlToSize56 string `json:"urlToSize56,omitempty"`
	UrlToSize64 string `json:"urlToSize64,omitempty"`
	UrlToSize80 string `json:"urlToSize80,omitempty"`
}
