/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a branch on which this build has been started.
type Branch struct {
	Name         string  `json:"name,omitempty"`
	InternalName string  `json:"internalName,omitempty"`
	Default_     bool    `json:"default,omitempty"`
	Unspecified  bool    `json:"unspecified,omitempty"`
	Active       bool    `json:"active,omitempty"`
	LastActivity string  `json:"lastActivity,omitempty"`
	GroupFlag    bool    `json:"groupFlag,omitempty"`
	Builds       *Builds `json:"builds,omitempty"`
}
