/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a paginated list of ProblemOccurrence entities.
type ProblemOccurrences struct {
	Count             int32               `json:"count,omitempty"`
	Href              string              `json:"href,omitempty"`
	NextHref          string              `json:"nextHref,omitempty"`
	PrevHref          string              `json:"prevHref,omitempty"`
	ProblemOccurrence []ProblemOccurrence `json:"problemOccurrence,omitempty"`
	Passed            int32               `json:"passed,omitempty"`
	Failed            int32               `json:"failed,omitempty"`
	NewFailed         int32               `json:"newFailed,omitempty"`
	Ignored           int32               `json:"ignored,omitempty"`
	Muted             int32               `json:"muted,omitempty"`
}
