/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents an issue with the test.
type Problem struct {
	Id                 string              `json:"id,omitempty"`
	Type_              string              `json:"type,omitempty"`
	Identity           string              `json:"identity,omitempty"`
	Href               string              `json:"href,omitempty"`
	Description        string              `json:"description,omitempty"`
	Mutes              *Mutes              `json:"mutes,omitempty"`
	Investigations     *Investigations     `json:"investigations,omitempty"`
	ProblemOccurrences *ProblemOccurrences `json:"problemOccurrences,omitempty"`
	Locator            string              `json:"locator,omitempty"`
}
