/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents the specific file change (in the scope of the commit).
type FileChange struct {
	BeforeRevision    string `json:"before-revision,omitempty"`
	AfterRevision     string `json:"after-revision,omitempty"`
	ChangeType        string `json:"changeType,omitempty"`
	ChangeTypeComment string `json:"changeTypeComment,omitempty"`
	File              string `json:"file,omitempty"`
	RelativeFile      string `json:"relative-file,omitempty"`
	Directory         bool   `json:"directory,omitempty"`
}
