/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents the user/trigger/dependency which caused this build to start.
type TriggeredBy struct {
	Type_       string      `json:"type,omitempty"`
	Details     string      `json:"details,omitempty"`
	Date        string      `json:"date,omitempty"`
	DisplayText string      `json:"displayText,omitempty"`
	RawValue    string      `json:"rawValue,omitempty"`
	User        *User       `json:"user,omitempty"`
	Build       *Build      `json:"build,omitempty"`
	BuildType   *BuildType  `json:"buildType,omitempty"`
	Properties  *Properties `json:"properties,omitempty"`
}
