/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a VCS change (commit).
type Change struct {
	Id                     int64                   `json:"id,omitempty"`
	Version                string                  `json:"version,omitempty"`
	InternalVersion        string                  `json:"internalVersion,omitempty"`
	Username               string                  `json:"username,omitempty"`
	Date                   string                  `json:"date,omitempty"`
	RegistrationDate       string                  `json:"registrationDate,omitempty"`
	Personal               bool                    `json:"personal,omitempty"`
	Href                   string                  `json:"href,omitempty"`
	WebUrl                 string                  `json:"webUrl,omitempty"`
	Comment                string                  `json:"comment,omitempty"`
	User                   *User                   `json:"user,omitempty"`
	Type_                  string                  `json:"type,omitempty"`
	SnapshotDependencyLink *SnapshotDependencyLink `json:"snapshotDependencyLink,omitempty"`
	Files                  *FileChanges            `json:"files,omitempty"`
	VcsRootInstance        *VcsRootInstance        `json:"vcsRootInstance,omitempty"`
	ParentChanges          *Changes                `json:"parentChanges,omitempty"`
	ParentRevisions        *Items                  `json:"parentRevisions,omitempty"`
	Attributes             *Properties             `json:"attributes,omitempty"`
	StoresProjectSettings  bool                    `json:"storesProjectSettings,omitempty"`
	Status                 *ChangeStatus           `json:"status,omitempty"`
	Commiter               *Commiter               `json:"commiter,omitempty"`
	CanEditComment         bool                    `json:"canEditComment,omitempty"`
	Locator                string                  `json:"locator,omitempty"`
}
