/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a locator string for filtering Agent entities.
type AgentLocator struct {
	// Is the agent authorized.
	Authorized bool `json:"authorized,omitempty"`
	// Build locator.
	Build string `json:"build,omitempty"`
	// Compatible build types locator.
	Compatible string `json:"compatible,omitempty"`
	// Is the agent connected.
	Connected bool `json:"connected,omitempty"`
	// For paginated calls, how many entities to return per page.
	Count int32 `json:"count,omitempty"`
	// Is the agent enabled.
	Enabled bool `json:"enabled,omitempty"`
	// Entity ID.
	Id int32  `json:"id,omitempty"`
	Ip string `json:"ip,omitempty"`
	// Supply multiple locators and return a union of the results.
	Item      string `json:"item,omitempty"`
	Name      string `json:"name,omitempty"`
	Parameter string `json:"parameter,omitempty"`
	// Agent pool locator.
	Pool string `json:"pool,omitempty"`
	// For paginated calls, from which entity to start rendering the page.
	Start int32 `json:"start,omitempty"`
}
