/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a build instance.
type Build struct {
	Id                          int64                   `json:"id,omitempty"`
	TaskId                      int64                   `json:"taskId,omitempty"`
	BuildTypeId                 string                  `json:"buildTypeId,omitempty"`
	BuildTypeInternalId         string                  `json:"buildTypeInternalId,omitempty"`
	Number                      string                  `json:"number,omitempty"`
	Status                      string                  `json:"status,omitempty"`
	State                       string                  `json:"state,omitempty"`
	Running                     bool                    `json:"running,omitempty"`
	Composite                   bool                    `json:"composite,omitempty"`
	FailedToStart               bool                    `json:"failedToStart,omitempty"`
	Personal                    bool                    `json:"personal,omitempty"`
	PercentageComplete          int32                   `json:"percentageComplete,omitempty"`
	BranchName                  string                  `json:"branchName,omitempty"`
	DefaultBranch               bool                    `json:"defaultBranch,omitempty"`
	UnspecifiedBranch           bool                    `json:"unspecifiedBranch,omitempty"`
	History                     bool                    `json:"history,omitempty"`
	Pinned                      bool                    `json:"pinned,omitempty"`
	Href                        string                  `json:"href,omitempty"`
	WebUrl                      string                  `json:"webUrl,omitempty"`
	QueuePosition               int32                   `json:"queuePosition,omitempty"`
	LimitedChangesCount         int32                   `json:"limitedChangesCount,omitempty"`
	ArtifactsDirectory          string                  `json:"artifactsDirectory,omitempty"`
	Links                       *Links                  `json:"links,omitempty"`
	StatusText                  string                  `json:"statusText,omitempty"`
	BuildType                   *BuildType              `json:"buildType,omitempty"`
	Comment                     *Comment                `json:"comment,omitempty"`
	Tags                        *Tags                   `json:"tags,omitempty"`
	PinInfo                     *Comment                `json:"pinInfo,omitempty"`
	User                        *User                   `json:"user,omitempty"`
	StartEstimate               string                  `json:"startEstimate,omitempty"`
	WaitReason                  string                  `json:"waitReason,omitempty"`
	FinishEstimate              string                  `json:"finishEstimate,omitempty"`
	DelayedByBuild              *Build                  `json:"delayedByBuild,omitempty"`
	PlannedAgent                *Agent                  `json:"plannedAgent,omitempty"`
	ApprovalInfo                *ApprovalInfo           `json:"approvalInfo,omitempty"`
	RunningInfo                 *ProgressInfo           `json:"running-info,omitempty"`
	CanceledInfo                *Comment                `json:"canceledInfo,omitempty"`
	QueuedDate                  string                  `json:"queuedDate,omitempty"`
	StartDate                   string                  `json:"startDate,omitempty"`
	FinishDate                  string                  `json:"finishDate,omitempty"`
	Triggered                   *TriggeredBy            `json:"triggered,omitempty"`
	LastChanges                 *Changes                `json:"lastChanges,omitempty"`
	Changes                     *Changes                `json:"changes,omitempty"`
	Revisions                   *Revisions              `json:"revisions,omitempty"`
	VersionedSettingsRevision   *Revision               `json:"versionedSettingsRevision,omitempty"`
	ArtifactDependencyChanges   *BuildChanges           `json:"artifactDependencyChanges,omitempty"`
	Agent                       *Agent                  `json:"agent,omitempty"`
	CompatibleAgents            *Agents                 `json:"compatibleAgents,omitempty"`
	TestOccurrences             *TestOccurrences        `json:"testOccurrences,omitempty"`
	ProblemOccurrences          *ProblemOccurrences     `json:"problemOccurrences,omitempty"`
	Artifacts                   *Files                  `json:"artifacts,omitempty"`
	RelatedIssues               *IssuesUsages           `json:"relatedIssues,omitempty"`
	Properties                  *Properties             `json:"properties,omitempty"`
	ResultingProperties         *Properties             `json:"resultingProperties,omitempty"`
	Attributes                  *Entries                `json:"attributes,omitempty"`
	Statistics                  *Properties             `json:"statistics,omitempty"`
	Metadata                    *Datas                  `json:"metadata,omitempty"`
	SnapshotDependencies        *Builds                 `json:"snapshot-dependencies,omitempty"`
	ArtifactDependencies        *Builds                 `json:"artifact-dependencies,omitempty"`
	CustomArtifactDependencies  *ArtifactDependencies   `json:"custom-artifact-dependencies,omitempty"`
	SettingsHash                string                  `json:"settingsHash,omitempty"`
	CurrentSettingsHash         string                  `json:"currentSettingsHash,omitempty"`
	ModificationId              string                  `json:"modificationId,omitempty"`
	ChainModificationId         string                  `json:"chainModificationId,omitempty"`
	ReplacementIds              *Items                  `json:"replacementIds,omitempty"`
	Related                     *Related                `json:"related,omitempty"`
	TriggeringOptions           *BuildTriggeringOptions `json:"triggeringOptions,omitempty"`
	UsedByOtherBuilds           bool                    `json:"usedByOtherBuilds,omitempty"`
	StatusChangeComment         *Comment                `json:"statusChangeComment,omitempty"`
	VcsLabels                   []VcsLabel              `json:"vcsLabels,omitempty"`
	DetachedFromAgent           bool                    `json:"detachedFromAgent,omitempty"`
	FinishOnAgentDate           string                  `json:"finishOnAgentDate,omitempty"`
	Customized                  bool                    `json:"customized,omitempty"`
	Customization               *Customizations         `json:"customization,omitempty"`
	ChangesCollectingInProgress bool                    `json:"changesCollectingInProgress,omitempty"`
	QueuedWaitReasons           *Properties             `json:"queuedWaitReasons,omitempty"`
	DownloadedArtifacts         *DownloadedArtifacts    `json:"downloadedArtifacts,omitempty"`
	FirstBuildWithSameChanges   *Build                  `json:"firstBuildWithSameChanges,omitempty"`
	Locator                     string                  `json:"locator,omitempty"`
}
