/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a server health item.
type HealthItem struct {
	Identity       string          `json:"identity,omitempty"`
	Severity       string          `json:"severity,omitempty"`
	HealthCategory *HealthCategory `json:"healthCategory,omitempty"`
}
