/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a locator string for filtering Tag entities.
type TagLocator struct {
	Name    string `json:"name,omitempty"`
	Owner   string `json:"owner,omitempty"`
	Private string `json:"private,omitempty"`
}
