/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents links to the last or previous VCS root check.
type VcsStatus struct {
	Current  *VcsCheckStatus `json:"current,omitempty"`
	Previous *VcsCheckStatus `json:"previous,omitempty"`
}
