/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents an investigation target.
type ProblemTarget struct {
	AnyProblem bool      `json:"anyProblem,omitempty"`
	Tests      *Tests    `json:"tests,omitempty"`
	Problems   *Problems `json:"problems,omitempty"`
}
