/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a locator string for filtering Project entities.
type ProjectLocator struct {
	// Project (direct or indirect parent) locator.
	AffectedProject string `json:"affectedProject,omitempty"`
	// Is archived.
	Archived bool `json:"archived,omitempty"`
	// Build locator.
	Build string `json:"build,omitempty"`
	// Build type locator.
	BuildType string `json:"buildType,omitempty"`
	// For paginated calls, how many entities to return per page.
	Count int32 `json:"count,omitempty"`
	// Default template locator.
	DefaultTemplate string `json:"defaultTemplate,omitempty"`
	Id              string `json:"id,omitempty"`
	InternalId      string `json:"internalId,omitempty"`
	// Supply multiple locators and return a union of the results.
	Item string `json:"item,omitempty"`
	Name string `json:"name,omitempty"`
	// Associated agent pool locator.
	Pool string `json:"pool,omitempty"`
	// Project (direct parent) locator.
	Project string `json:"project,omitempty"`
	// Project feature locator.
	ProjectFeature string `json:"projectFeature,omitempty"`
	// For paginated calls, from which entity to start rendering the page.
	Start int32  `json:"start,omitempty"`
	Uuid  string `json:"uuid,omitempty"`
	// VCS root locator.
	VcsRoot string `json:"vcsRoot,omitempty"`
	// Is virtual (default=false).
	Virtual bool `json:"virtual,omitempty"`
}
