/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Collection of artifacts metadata which were downloaded from dependencies of this build or delivered to ones depending on this build.
type DownloadedArtifacts struct {
	UnfilteredCount int32          `json:"unfilteredCount,omitempty"`
	DownloadInfo    []DownloadInfo `json:"downloadInfo,omitempty"`
	Count           int32          `json:"count,omitempty"`
}
