/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a metric value.
type MetricValue struct {
	Name  string      `json:"name,omitempty"`
	Value float64     `json:"value,omitempty"`
	Tags  *MetricTags `json:"tags,omitempty"`
}
