/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ArtifactDownloadInfo struct {
	Path              string `json:"path,omitempty"`
	DownloadTimestamp string `json:"downloadTimestamp,omitempty"`
}
