/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a named Entries entity.
type MetaData struct {
	Id      string   `json:"id,omitempty"`
	Entries *Entries `json:"entries,omitempty"`
}
