/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a relation between the issue and the Changes entity.
type IssueUsage struct {
	Changes *Changes `json:"changes,omitempty"`
	Issue   *Issue   `json:"issue,omitempty"`
}
