/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents user approval rule and its current status for the given build.
type UserApprovalRule struct {
	Approved bool  `json:"approved,omitempty"`
	User     *User `json:"user,omitempty"`
}
