/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a locator string for filtering AgentPool entities.
type AgentPoolLocator struct {
	// Pool's agents locator.
	Agent string `json:"agent,omitempty"`
	Id    string `json:"id,omitempty"`
	// Supply multiple locators and return a union of the results.
	Item string `json:"item,omitempty"`
	Name string `json:"name,omitempty"`
	// Pool's associated projects locator.
	Project string `json:"project,omitempty"`
}
