/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a TeamCity node.
type Node struct {
	Id                        string                     `json:"id,omitempty"`
	Url                       string                     `json:"url,omitempty"`
	State                     string                     `json:"state,omitempty"`
	Role                      string                     `json:"role,omitempty"`
	Current                   bool                       `json:"current,omitempty"`
	EnabledResponsibilities   *EnabledResponsibilities   `json:"enabledResponsibilities,omitempty"`
	DisabledResponsibilities  *DisabledResponsibilities  `json:"disabledResponsibilities,omitempty"`
	EffectiveResponsibilities *EffectiveResponsibilities `json:"effectiveResponsibilities,omitempty"`
}
