/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a set of responsibilities that are currently disabled but can be enabled on a TeamCity node.
type DisabledResponsibilities struct {
	Count          int32            `json:"count,omitempty"`
	Responsibility []Responsibility `json:"responsibility,omitempty"`
}
