/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents the list of the repository Branch entities with their recent revisions.
type RepositoryState struct {
	Timestamp string          `json:"timestamp,omitempty"`
	Count     int32           `json:"count,omitempty"`
	Branch    []BranchVersion `json:"branch,omitempty"`
}
