/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a VCS root.
type VcsRoot struct {
	Id                        string            `json:"id,omitempty"`
	InternalId                string            `json:"internalId,omitempty"`
	Uuid                      string            `json:"uuid,omitempty"`
	Name                      string            `json:"name,omitempty"`
	VcsName                   string            `json:"vcsName,omitempty"`
	ModificationCheckInterval int32             `json:"modificationCheckInterval,omitempty"`
	Href                      string            `json:"href,omitempty"`
	Project                   *Project          `json:"project,omitempty"`
	Properties                *Properties       `json:"properties,omitempty"`
	VcsRootInstances          *VcsRootInstances `json:"vcsRootInstances,omitempty"`
	RepositoryIdStrings       *Items            `json:"repositoryIdStrings,omitempty"`
	ProjectLocator            string            `json:"projectLocator,omitempty"`
	Locator                   string            `json:"locator,omitempty"`
}
