/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a VCS-side label of this build's sources.
type VcsLabel struct {
	Text            string           `json:"text,omitempty"`
	FailureReason   string           `json:"failureReason,omitempty"`
	Status          string           `json:"status,omitempty"`
	BuildId         int64            `json:"buildId,omitempty"`
	VcsRootInstance *VcsRootInstance `json:"vcs-root-instance,omitempty"`
}
