/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a paginated list of Change entities.
type Changes struct {
	Href     string   `json:"href,omitempty"`
	Change   []Change `json:"change,omitempty"`
	NextHref string   `json:"nextHref,omitempty"`
	PrevHref string   `json:"prevHref,omitempty"`
	Count    int32    `json:"count,omitempty"`
}
