/*
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2018.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Represents a project state field (as of now, limited to the read-only state of project).
type StateField struct {
	Value     bool `json:"value,omitempty"`
	Inherited bool `json:"inherited,omitempty"`
}
